"""What an inbound job email actually means.

Ingestion used to ask one question — "does this contain job URLs?" — and throw
away everything else. That discarded the highest-signal mail in the box. These
are all real subjects from a week of one inbox:

    Reminder: Principal Engineer at KnackLabs      an employer wants *you* to apply
    Missed message from Blitzy?                    an employer messaged you
    Questionnaire still pending from Virtana       an application of yours is stalled
    IT/Tech Jobs Picked for Your Experience        a broadcast digest
    Be first to apply-with Neo                     marketing
    hirist.tech Registration                       account admin

The first three are about *you*. A digest is about everyone. Treating them
identically is what made a stalled application indistinguishable from an advert.

The classifier is deliberately rules-over-LLM: it runs on every message of every
scan, it must work with no API key, and the phrasing of these templates is
stable — they are generated by a handful of job boards, not written by people.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

# Ordered by how much they mean to the user, most first.
INVITE_TO_APPLY = "invite_to_apply"
APPLICATION_UPDATE = "application_update"
SINGLE_POSTING = "single_posting"
JOB_DIGEST = "job_digest"
MARKETING = "marketing"
ACCOUNT_ADMIN = "account_admin"
UNKNOWN = "unknown"

# Intents where somebody is addressing this user about a specific role, rather
# than broadcasting a list. These are worth surfacing above ordinary discovery.
INBOUND_INTEREST = frozenset({INVITE_TO_APPLY, APPLICATION_UPDATE})


@dataclass
class Intent:
    kind: str
    confidence: int  # 0-10
    company: str = ""
    reason: str = ""

    @property
    def is_inbound_interest(self) -> bool:
        return self.kind in INBOUND_INTEREST

    @property
    def is_actionable(self) -> bool:
        """Worth the user's attention, as opposed to worth ingesting quietly."""
        return self.kind in INBOUND_INTEREST


# ── patterns ─────────────────────────────────────────────────────────────────
# Checked in order: the first match wins, so the most specific go first. Account
# admin outranks everything because "verify your email" from a job board is not
# a job however many job words surround it.

_ADMIN = (
    r"\bverify your (email|account)\b",
    r"\b(email|account) verification\b",
    r"\bregistration\b",
    r"\breset your password\b",
    r"\bwelcome to\b",
    r"\bconfirm your (email|subscription)\b",
    r"\bprofile (is )?(incomplete|updated)\b",
)

_APPLICATION_UPDATE = (
    r"\bquestionnaire\b",
    r"\bassessment (pending|invite|invitation)\b",
    r"\bcomplete your application\b",
    r"\bapplication (is )?(pending|incomplete|received|under review)\b",
    r"\byour application (to|for|at)\b",
    r"\baction (required|needed)\b",
    r"\bnext steps?\b",
    r"\bawaiting your (response|reply)\b",
)

_INVITE = (
    r"\bmissed message from\b",
    r"\bmessage from .{2,40}\?$",
    r"^reminder:\s",
    r"\binvit(ed|ation) to apply\b",
    r"\bwants? to (connect|hire|talk)\b",
    r"\byou would be a great (fit|match)\b",
    r"\bwe think you.{0,4}d be\b",
    r"\brecruiter (viewed|is interested)\b",
    r"\bshortlisted\b",
    r"\bemployer (is )?interested\b",
)

_MARKETING = (
    r"\bbe first to apply\b",
    r"\bunlock your\b",
    r"\bstill searching\b",
    r"\bperfect job is here\b",
    r"\bupgrade\b",
    r"\bpremium\b",
    r"\bwebinar\b",
    r"\bcourse\b",
    r"\bcertification\b",
    r"\bsale\b",
    r"\bdiscount\b",
    r"\bresume (writing|services)\b",
)

# A digest announces a quantity or a plural set of roles.
_DIGEST = (
    r"\b\d+\+?\s+(matching\s+)?(jobs|roles|openings|opportunities)\b",
    r"\band \d+ more jobs?\b",
    r"\bjobs? (picked|curated|matching|based on|for you)\b",
    r"\b(job|jobs) alert\b",
    r"\bnew job opportunities\b",
    r"\btop (tech )?jobs\b",
    r"\bjobs you might have missed\b",
    r"\bmatch(ing|es)?\s+your\s+(profile|experience|preferences|skills)\b",
    r"\bjobs?\s+that\s+match\b",
    r"\brecommended jobs\b",
)

# One named role: "Hiring | AI Engineer at Tiger Analytics", "SRE 3 role at eBay",
# "Job | Forward Deployed Engineer in Bengaluru".
_SINGLE = (
    r"\bhiring\b.*\bat\b",
    # Not anchored to the start: these subjects often open with an emoji or a
    # sender prefix — "✉️ Job | Forward Deployed Engineer in Bengaluru".
    r"(^|[^\w])job\s*[|:]",
    r"\brole at\b",
    r"\bopening for\b",
    r"\bposition (at|for)\b",
    r"@\s*[A-Z]",
    # "Staff Software Engineer, Reliability at Metropolis Healthcare" — a named
    # role at a named employer. Safe here because digests are matched first, so
    # "…at Shell and 11 more jobs" has already been claimed as a list.
    r"\b(engineer|developer|manager|analyst|architect|lead|scientist|designer"
    r"|specialist|consultant|administrator|sre|devops)\b[^|]*\bat\s+[A-Z]",
)

_COMPANY_PATTERNS = (
    r"\bmissed message from\s+([A-Z][\w&.\- ]{1,40}?)\s*\??$",
    r"\bpending from\s+([A-Z][\w&.\- ]{1,40}?)\s*$",
    r"^reminder:\s+.*?\bat\s+([A-Z][\w&.\- ]{1,40}?)\s*$",
    r"\bat\s+([A-Z][\w&.\- ]{1,40}?)(?::|\s*$)",
)


def _any(patterns: tuple[str, ...], text: str) -> str:
    for p in patterns:
        if re.search(p, text, re.I | re.M):
            return p
    return ""


def extract_company(subject: str) -> str:
    for p in _COMPANY_PATTERNS:
        m = re.search(p, (subject or "").strip(), re.I | re.M)
        if m:
            name = (m.group(1) or "").strip(" -–|:,.")
            # "and 11 more jobs" is a digest tail, not an employer.
            if name and not re.match(r"^\d", name) and len(name) > 1:
                return name[:60]
    return ""


_ROLE_STOPWORDS = frozenset({
    "the", "a", "an", "and", "or", "at", "in", "for", "of", "to", "with", "role",
    "job", "jobs", "new", "you", "your", "would", "be", "great", "fit", "match",
    "senior", "sr", "junior", "jr", "lead", "staff", "principal", "hiring",
    "reminder", "opening", "position", "apply", "more", "remote",
})


def _significant_words(text: str) -> set[str]:
    words = re.findall(r"[a-z0-9]+", (text or "").lower())
    return {w for w in words if len(w) > 2 and w not in _ROLE_STOPWORDS}


def link_matches_subject(subject: str, title: str, company: str = "") -> bool:
    """Is this link the role the subject is about, or a related-jobs footer entry?

    An invite names one role — "Site Reliability Engineer 3 role at eBay" — but
    the mail carries four more openings underneath it. Flagging all five as
    "an employer approached you" would drown the real signal in the noise it
    exists to rise above, so only the link that matches the subject counts.
    """
    subject_words = _significant_words(subject)
    if not subject_words:
        return False

    hint = extract_company(subject)
    if hint and company and hint.lower() in company.lower():
        return True
    if hint and hint.lower() in (title or "").lower():
        return True

    # Drop the employer's name before comparing roles, or every link in a
    # single-company mail would match on the company alone.
    role_words = subject_words - _significant_words(hint)
    overlap = role_words & _significant_words(title)
    return len(overlap) >= 2


def classify_intent(subject: str, body: str = "", sender: str = "") -> Intent:
    """Decide what a message is. Subject carries almost all of the signal.

    Body is used only to break ties, because these templates put their meaning in
    the subject line and their body in 14KB of tracking markup.
    """
    subj = (subject or "").strip()
    if not subj:
        return Intent(UNKNOWN, 0, reason="no subject")

    hay = subj if not body else f"{subj}\n{body[:2000]}"
    company = extract_company(subj)

    if hit := _any(_ADMIN, subj):
        return Intent(ACCOUNT_ADMIN, 9, company, f"admin: {hit}")

    # Before invite: "Reminder: questionnaire pending" is an application, not a
    # fresh invitation, and both patterns would otherwise match it.
    if hit := _any(_APPLICATION_UPDATE, hay):
        return Intent(APPLICATION_UPDATE, 9, company, f"application: {hit}")

    if hit := _any(_INVITE, subj):
        return Intent(INVITE_TO_APPLY, 8, company, f"invite: {hit}")

    # Digest before single: "…at Shell and 11 more jobs" is a list, and the
    # single-role patterns would otherwise claim it on the "at" alone.
    if hit := _any(_DIGEST, subj):
        return Intent(JOB_DIGEST, 8, "", f"digest: {hit}")

    if hit := _any(_MARKETING, subj):
        return Intent(MARKETING, 7, company, f"marketing: {hit}")

    if hit := _any(_SINGLE, subj):
        return Intent(SINGLE_POSTING, 7, company, f"single: {hit}")

    return Intent(UNKNOWN, 2, company, "no pattern matched")
