"""Shared LaTeX preamble + density ladder for every résumé template.

Why this exists
---------------
Each template used to carry its own copy of the preamble. Twelve copies meant
twelve subtly different documents: some suppressed ligatures and some did not,
some defined ``\\entry`` and some did not (so emitting it silently failed the
compile), and none of them controlled page breaks. The parts of a résumé that
have to be *correct* — ATS text extraction, right-flush alignment, widows,
where a page breaks — are identical for every design, so they live here once.
What a template still owns is how it *looks*: colour, section rules, header
arrangement, serif vs sans.

The generated ``.tex`` stays self-contained (the preamble is inlined, not
``\\input``), so a user can drop it straight into Overleaf.

Density
-------
``DENSITY_LADDER`` is ordered roomiest → densest. The builder compiles, counts
pages, and picks the roomiest rung that still meets the page target, which is
what makes "one page" or "two pages" a real guarantee instead of a hope.
"""

from __future__ import annotations

import re
from dataclasses import dataclass


@dataclass(frozen=True)
class Density:
    """One rung of the fit ladder. All lengths are LaTeX literals."""

    name: str
    base_pt: str          # documentclass size — article only accepts 10/11/12pt
    margin: str           # left/right margin
    top: str
    bottom: str
    linespread: str
    item_sep: str         # between bullets
    entry_sep: str        # above a role/project entry
    sec_before: str       # above a section heading
    sec_after: str        # below a section heading
    name_size: str        # \fontsize arguments for the candidate's name
    contact_size: str


# Roomiest → densest. Steps are deliberately small: a résumé that only just
# overflows should lose 2pt of leading, not drop a whole font size.
DENSITY_LADDER: tuple[Density, ...] = (
    Density("airy",     "11pt", "1.90cm", "1.55cm", "1.45cm", "1.05", "2.8pt", "6pt", "12pt", "5pt", "{18}{21}", "{9}{11}"),
    Density("relaxed",  "11pt", "1.75cm", "1.40cm", "1.30cm", "1.02", "2.4pt", "5pt", "10pt", "4pt", "{17}{20}", "{8.8}{11}"),
    Density("normal",   "10pt", "1.55cm", "1.25cm", "1.20cm", "1.00", "2.0pt", "4.5pt", "9pt",  "3.5pt", "{16}{19}", "{8.6}{10.5}"),
    Density("snug",     "10pt", "1.45cm", "1.15cm", "1.10cm", "0.99", "1.6pt", "3.5pt", "8pt",  "3pt", "{15}{18}", "{8.4}{10}"),
    Density("compact",  "10pt", "1.30cm", "1.05cm", "1.00cm", "0.97", "1.3pt", "3pt", "7pt",  "2.5pt", "{14.5}{17}", "{8.2}{10}"),
    Density("tight",    "10pt", "1.15cm", "0.95cm", "0.90cm", "0.95", "1.0pt", "2pt", "6pt",  "2pt", "{14}{16}", "{8}{9.5}"),
)

DEFAULT_DENSITY = 2  # "normal" — where a fit search starts


def density_by_name(name: str) -> int:
    for i, d in enumerate(DENSITY_LADDER):
        if d.name == name:
            return i
    return DEFAULT_DENSITY


def _pdf_safe(text: str) -> str:
    """Plain ASCII-ish string for PDF metadata (hyperref chokes on commands)."""
    cleaned = re.sub(r"[\\{}#%&$_^~]", "", text or "")
    return re.sub(r"\s+", " ", cleaned).strip()[:120]


def build_preamble(
    density: Density,
    *,
    pdf_title: str = "Resume",
    pdf_author: str = "",
) -> str:
    """The full preamble: documentclass through the last macro definition."""
    return rf"""% ─────────────────────────────────────────────────────────────────────────
% Generated by shortlistr. Self-contained: paste into Overleaf as-is.
%
% The rules below are what make the PDF survive an applicant-tracking system:
%   * one column, so extracted text comes out in reading order
%   * no tables, tikz, graphics, headers or footers — parsers drop all of those
%   * ligatures off: "fi" as one glyph makes an ATS read "Proficient" as
%     "Pro<fi>cient" and miss the keyword
%   * hyphenation off: a keyword split across two lines is two non-words
%   * section titles are ordinary mixed-case words, because parsers match on
%     exactly those strings
% ─────────────────────────────────────────────────────────────────────────
\documentclass[{density.base_pt},a4paper]{{article}}

% Ligature suppression has to branch: \DisableLigatures is pdfTeX-only and
% errors out under XeTeX, which is the engine tectonic runs.
\usepackage{{iftex}}
\ifPDFTeX
  \usepackage[T1]{{fontenc}}
  \usepackage[utf8]{{inputenc}}
  \usepackage{{lmodern}}
  \DisableLigatures[f,q,t,T,Q]{{encoding = *, family = *}}
\else
  \usepackage{{fontspec}}
  % By filename, not family name: "Latin Modern Roman" only resolves when the
  % OTF is installed system-wide, which it is not under tectonic.
  \setmainfont{{lmroman10-regular.otf}}[
    BoldFont       = lmroman10-bold.otf,
    ItalicFont     = lmroman10-italic.otf,
    BoldItalicFont = lmroman10-bolditalic.otf,
    Ligatures      = NoCommon]
  \setsansfont{{lmsans10-regular.otf}}[
    BoldFont       = lmsans10-bold.otf,
    ItalicFont     = lmsans10-oblique.otf,
    Ligatures      = NoCommon]
\fi
\usepackage[protrusion=true,expansion=false]{{microtype}}
\usepackage[a4paper,left={density.margin},right={density.margin},top={density.top},bottom={density.bottom}]{{geometry}}
\usepackage{{enumitem}}
\usepackage{{xcolor}}
\usepackage{{needspace}}
\usepackage[hidelinks,
            pdftitle={{{_pdf_safe(pdf_title)}}},
            pdfauthor={{{_pdf_safe(pdf_author)}}},
            pdfcreator={{Shortlistr}}]{{hyperref}}

\pagestyle{{empty}}
\linespread{{{density.linespread}}}
\setlength{{\parindent}}{{0pt}}
\setlength{{\parskip}}{{0pt}}

% ── Page-break discipline ────────────────────────────────────────────────
% A résumé is read as whole blocks. A single bullet stranded at the top of
% page two, or a job title alone at the bottom of page one, reads as a
% formatting accident — so breaking there is made prohibitively expensive
% rather than merely discouraged.
\widowpenalty=10000
\clubpenalty=10000
\brokenpenalty=10000
\interlinepenalty=200
\raggedbottom

% Ragged right instead of justified. Justification needs hyphenation to avoid
% rivers, and hyphenation is what breaks keywords in half for the parser.
\raggedright
\hyphenpenalty=10000
\exhyphenpenalty=10000
\tolerance=3000
\emergencystretch=2em

% ── Density (set by the fit search, not by hand) ─────────────────────────
\newlength{{\cvitemsep}}   \setlength{{\cvitemsep}}{{{density.item_sep}}}
\newlength{{\cventryskip}} \setlength{{\cventryskip}}{{{density.entry_sep}}}
\newlength{{\cvsecbefore}} \setlength{{\cvsecbefore}}{{{density.sec_before}}}
\newlength{{\cvsecafter}}  \setlength{{\cvsecafter}}{{{density.sec_after}}}

\setlist[itemize]{{leftmargin=1.1em, itemsep=\cvitemsep, parsep=0pt,
                  topsep=3pt, partopsep=0pt, label=\textbullet}}

% ── Alignment primitive ──────────────────────────────────────────────────
% Left text and right text on one baseline, the right one flush to the margin.
%
% \raggedright (above) sets \rightskip to infinite stretch, which swallows
% \hfill — that is why dates used to land at a different x-position on every
% entry. Cancelling \rightskip fixes the date column but re-justifies the left
% text, which only shows up once a title is too long for one line: a degree like
% "Executive PhD — Artificial Intelligence & Machine Learning (Pursuing),
% National Institute of Technology (NIT) Rourkela, India" came out stretched
% across two lines with rivers of white space through it.
%
% So the date is measured first and the title is set ragged-right in a box of
% exactly the remaining width. The outer paragraph is then a single line holding
% two boxes — nothing for justification to stretch — and the title wraps on its
% own terms. Text extraction order is unchanged: title, then date.
\newsavebox{{\cvwhenbox}}
\newcommand{{\cvsplit}}[2]{{%
  \begingroup
  \sbox\cvwhenbox{{#2}}%
  \rightskip=0pt\parfillskip=0pt\relax
  \noindent
  \parbox[t]{{\dimexpr\linewidth-\wd\cvwhenbox-1em\relax}}{{\raggedright #1}}%
  \hfill\usebox\cvwhenbox\par
  \endgroup
}}

% ── Hooks a template overrides ───────────────────────────────────────────
\definecolor{{cvaccent}}{{HTML}}{{1A1A1A}}
\definecolor{{cvmuted}}{{HTML}}{{4A4A4A}}
\newcommand{{\cvsectionfont}}[1]{{{{\large\bfseries #1}}}}
\newcommand{{\cvsectionrule}}{{\vspace{{1.5pt}}\hrule height 0.6pt\relax}}
\newcommand{{\cventryfont}}[1]{{\textbf{{#1}}}}
\newcommand{{\cvdatefont}}[1]{{{{\small #1}}}}
\newcommand{{\cvmetafont}}[1]{{{{\small\itshape\color{{cvmuted}} #1}}}}
\newcommand{{\cvnamefont}}[1]{{{{\fontsize{density.name_size}\selectfont\bfseries #1}}}}
\newcommand{{\cvcontactfont}}[1]{{{{\fontsize{density.contact_size}\selectfont #1}}}}
% The line of role keywords above the contact details. Worth its own slot: it
% is the densest concentration of title keywords on the page, and joining it
% into the contact line with a separator buried it mid-sentence between a
% phone number and a GitHub URL.
\newcommand{{\cvheadline}}[1]{{{{\itshape #1}}\par\vspace{{2pt}}}}

% ── Structure ────────────────────────────────────────────────────────────
% \needspace reserves room so a heading is never the last thing on a page,
% and \nobreak keeps the first entry attached to the heading above it.
\newcommand{{\cvsection}}[1]{{%
  \needspace{{5\baselineskip}}%
  \vspace{{\cvsecbefore}}%
  {{\cvsectionfont{{#1}}}}%
  \cvsectionrule
  \par\nobreak\vspace{{\cvsecafter}}%
}}

% One role: what they did on the left, when on the right, same line.
\newcommand{{\entry}}[2]{{%
  \needspace{{4\baselineskip}}%
  \vspace{{\cventryskip}}%
  \cvsplit{{\cventryfont{{#1}}}}{{\cvdatefont{{#2}}}}%
  \nobreak\vspace{{0.5pt}}%
}}

% The line under a role — company, location.
\newcommand{{\entrymeta}}[1]{{\cvmetafont{{#1}}\par\nobreak\vspace{{1pt}}}}

% Header block. Templates that want a different arrangement redefine it.
\newcommand{{\cvheader}}[2]{{%
  \cvnamefont{{#1}}\par\vspace{{3pt}}%
  \cvcontactfont{{#2}}\par\vspace{{3pt}}%
  {{\color{{cvaccent}}\hrule height 0.9pt}}%
  \vspace{{2pt}}%
}}
"""
